name: 난곡신일교회
description: Template for a video blog.
url: 'http://sjmw1030.github.io'
baseurl: '/nangokvideos'
email: nangokshinil@gmail.com
twitter: https://twitter.com/nangokshinil
youtube: https://www.youtube.com/nangokshinil
facebook: https://www.facebook.com/nangokshinil
google_analytics: 'UA-00000000-1'

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video
